/**
 * Regenerate the Claude Code / Cowork Penopta plugin (skills + remote MCP).
 *
 * Writes:
 *   plugins/claude/penopta/…              (installable plugin)
 *   .claude-plugin/marketplace.json       (repo marketplace entry)
 *
 * Does not submit to Anthropic’s directories (maintainer checklist lives in
 * docs/private/claude-directory.md).
 *
 * Usage (from penopta-app):
 *   npm run plugins:publish:claude
 */

import {
  copyFileSync,
  existsSync,
  mkdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { composeSyncSkill } from "@/lib/integrations/skill";
import { SYNC_SKILL_VERSION } from "@/lib/integrations/skill-version";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..");

const CONFIG_PATH = join(ROOT, "plugins/claude/config.json");
const PLUGIN_DIR = join(ROOT, "plugins/claude/penopta");
const MARKETPLACE_PATH = join(ROOT, ".claude-plugin/marketplace.json");
const INTEGRATIONS_DIR = join(ROOT, "src/lib/integrations");
const BRAND_ICON_PATH = join(ROOT, "public/brand/icon.png");

type SkillConfig = {
  name: string;
  description: string;
  /** `sync` → compose Claude hourly sync skill; else filename under integrations/. */
  source: string;
};

type PluginConfig = {
  pluginName: string;
  pluginVersion: string;
  description: string;
  author: { name: string; email?: string; url?: string };
  homepage?: string;
  keywords?: string[];
  mcpUrl: string;
  skills: SkillConfig[];
};

function loadConfig(): PluginConfig {
  const raw = JSON.parse(readFileSync(CONFIG_PATH, "utf8")) as PluginConfig;
  if (!raw.pluginName?.trim()) {
    throw new Error(`${CONFIG_PATH}: missing pluginName`);
  }
  if (!raw.mcpUrl?.trim()) {
    throw new Error(`${CONFIG_PATH}: missing mcpUrl`);
  }
  if (!Array.isArray(raw.skills) || raw.skills.length === 0) {
    throw new Error(`${CONFIG_PATH}: skills must be a non-empty array`);
  }
  for (const skill of raw.skills) {
    if (!skill.name?.trim() || !skill.description?.trim() || !skill.source?.trim()) {
      throw new Error(
        `${CONFIG_PATH}: each skill needs name, description, and source`,
      );
    }
  }
  if (!raw.pluginVersion?.trim()) {
    throw new Error(`${CONFIG_PATH}: missing pluginVersion`);
  }
  return raw;
}

function yamlQuote(value: string): string {
  return `"${value
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"')
    .replace(/\n/g, "\\n")}"`;
}

function yamlFrontmatter(name: string, description: string): string {
  const safeDescription = description
    .replace(/[\u201C\u201D]/g, '"')
    .replace(/[\u2018\u2019]/g, "'")
    .replace(/[\u2013\u2014]/g, "-")
    .replace(/\s+/g, " ")
    .trim();
  return [
    "---",
    `name: ${yamlQuote(name)}`,
    `description: ${yamlQuote(safeDescription)}`,
    "---",
    "",
  ].join("\n");
}

const PLUGIN_SYNC_SCOPE_NOTE =
  "This skill is **sync-only** (hourly schedule or an explicit “sync Penopta now”). " +
  "For questions about projects, threads, or what someone worked on, use the " +
  "`penopta-context` skill and Penopta MCP read tools — do not run discovery or `sync_threads` for Q&A.";

function adaptSkillForPlugin(body: string): string {
  const adapted = body
    .replaceAll(
      "Re-copy Instructions from Penopta → Integrations, then re-run once.",
      "Update or reinstall the Penopta Claude plugin (`npm run plugins:publish:claude`, then reinstall), or re-copy Instructions from Penopta → Integrations, then re-run once.",
    )
    .replaceAll(
      "Re-copy Instructions from Penopta → Integrations.",
      "Update or reinstall the Penopta Claude plugin, or re-copy Instructions from Penopta → Integrations.",
    )
    .replaceAll(
      "tell the user to re-copy Instructions from Penopta → Integrations",
      "tell the user to update/reinstall the Penopta Claude plugin (or re-copy Instructions from Penopta → Integrations)",
    );

  const versionComment = /^(<!-- penopta-sync-skill-version: \d+ -->\s*)/;
  if (versionComment.test(adapted)) {
    return adapted.replace(versionComment, `$1${PLUGIN_SYNC_SCOPE_NOTE}\n\n`);
  }
  return `${PLUGIN_SYNC_SCOPE_NOTE}\n\n${adapted}`;
}

function stripAuthoringComments(raw: string): string {
  return raw.replace(/^<!--[\s\S]*?-->\s*/, "").trim();
}

async function resolveSkillBody(skill: SkillConfig): Promise<{
  body: string;
  generatedNote: string;
}> {
  if (skill.source === "sync") {
    const body = adaptSkillForPlugin(await composeSyncSkill("claude"));
    return {
      body,
      generatedNote: `<!-- Generated by npm run plugins:publish:claude — do not edit. Source: sync-skill + SYNC_SKILL_VERSION=${SYNC_SKILL_VERSION} -->`,
    };
  }

  const path = join(INTEGRATIONS_DIR, skill.source);
  if (!existsSync(path)) {
    throw new Error(`Skill source not found: ${path}`);
  }
  return {
    body: stripAuthoringComments(readFileSync(path, "utf8")),
    generatedNote: `<!-- Generated by npm run plugins:publish:claude — do not edit. Source: src/lib/integrations/${skill.source} -->`,
  };
}

function writeJson(path: string, value: unknown): void {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, `${JSON.stringify(value, null, 2)}\n`);
}

function writeSetupSkill(pluginDir: string, mcpUrl: string): void {
  const skillDir = join(pluginDir, "skills", "SETUP");
  mkdirSync(skillDir, { recursive: true });
  const body = [
    yamlFrontmatter(
      "SETUP",
      "Guide the user through connecting the Penopta remote MCP connector (OAuth) after installing this plugin.",
    ),
    "<!-- Generated by npm run plugins:publish:claude — do not edit. -->",
    "",
    "Help the user finish Penopta setup after installing this plugin.",
    "",
    "## Goal",
    "",
    "Ensure the bundled Penopta MCP server is connected and the user is signed in with Penopta OAuth.",
    "",
    "## Steps",
    "",
    "1. Confirm the plugin is enabled. The MCP server key is `penopta`.",
    `2. The remote MCP URL is \`${mcpUrl}\` (same server as the Claude Connectors Directory listing).`,
    "3. Ask the user to approve the Penopta OAuth / Sign in with Penopta prompt if it appears.",
    "4. Call `penopta_verify` to confirm identity and active org.",
    "5. If verify fails, call `penopta_diagnose` and walk them through reconnecting the connector.",
    "6. Point them at https://www.penopta.com/docs/claude-connector and https://app.penopta.com/integrations/claude for full product setup (optional hourly sync + Claude in Chrome).",
    "",
    "Do not invent API keys or endpoints. Auth is OAuth only.",
    "",
  ].join("\n");
  writeFileSync(join(skillDir, "SKILL.md"), body);
}

function writePluginReadme(pluginDir: string, config: PluginConfig): void {
  const md = `# Penopta (Claude plugin)

Skills + remote MCP for Claude Code and Cowork.

- **MCP:** \`${config.mcpUrl}\` (same as the Claude Connectors Directory connector)
- **Docs:** ${config.homepage ?? "https://www.penopta.com/docs/claude-connector"}
- **Privacy:** https://penopta.com/privacy

## Install (local / marketplace)

From a checkout of this repo after \`npm run plugins:publish:claude\`:

\`\`\`bash
claude plugin marketplace add .
claude plugin install penopta@penopta-claude
\`\`\`

Or load once: \`claude --plugin-dir plugins/claude/penopta\`.

## Public directory

Plugin Directory submission needs a **public** GitHub URL to this plugin folder
(or a public mirror of it). Submit at https://platform.claude.com/plugins/submit.

Regenerate with \`npm run plugins:publish:claude\` — do not hand-edit \`skills/\`.
`;
  writeFileSync(join(pluginDir, "README.md"), md);
}

async function main(): Promise<void> {
  const config = loadConfig();

  if (!existsSync(BRAND_ICON_PATH)) {
    throw new Error(`Missing brand icon: ${BRAND_ICON_PATH}`);
  }

  rmSync(PLUGIN_DIR, { recursive: true, force: true });
  mkdirSync(join(PLUGIN_DIR, ".claude-plugin"), { recursive: true });

  const assetsDir = join(PLUGIN_DIR, "assets");
  mkdirSync(assetsDir, { recursive: true });
  copyFileSync(BRAND_ICON_PATH, join(assetsDir, "icon.png"));

  const skillPaths: string[] = [];
  for (const skill of config.skills) {
    const { body, generatedNote } = await resolveSkillBody(skill);
    const skillDir = join(PLUGIN_DIR, "skills", skill.name);
    mkdirSync(skillDir, { recursive: true });
    const skillMd = [
      yamlFrontmatter(skill.name, skill.description),
      generatedNote,
      "",
      body.trim(),
      "",
    ].join("\n");
    const skillPath = join(skillDir, "SKILL.md");
    writeFileSync(skillPath, skillMd);
    skillPaths.push(skillPath);
  }

  writeSetupSkill(PLUGIN_DIR, config.mcpUrl);
  skillPaths.push(join(PLUGIN_DIR, "skills/SETUP/SKILL.md"));

  writeJson(join(PLUGIN_DIR, ".mcp.json"), {
    mcpServers: {
      penopta: {
        type: "http",
        url: config.mcpUrl,
      },
    },
  });

  writeJson(join(PLUGIN_DIR, ".claude-plugin/plugin.json"), {
    name: config.pluginName,
    version: config.pluginVersion,
    description: config.description,
    author: config.author,
    homepage: config.homepage,
    keywords: config.keywords,
    // Default locations: skills/ and .mcp.json at plugin root.
  });

  writePluginReadme(PLUGIN_DIR, config);

  writeJson(MARKETPLACE_PATH, {
    name: "penopta-claude",
    owner: {
      name: config.author.name,
      email: config.author.email,
      url: config.author.url,
    },
    metadata: {
      description: "Penopta plugins for Claude Code and Cowork",
      version: config.pluginVersion,
    },
    plugins: [
      {
        name: config.pluginName,
        source: "./plugins/claude/penopta",
        description: config.description,
        version: config.pluginVersion,
        author: config.author,
        homepage: config.homepage,
        keywords: config.keywords,
        category: "productivity",
      },
    ],
  });

  console.log("");
  console.log(
    `Published Claude Penopta plugin v${config.pluginVersion} (hourly sync skill v${SYNC_SKILL_VERSION})`,
  );
  for (const skillPath of skillPaths) {
    console.log(`  skill   ${skillPath}`);
  }
  console.log(`  plugin  ${PLUGIN_DIR}`);
  console.log(`  market  ${MARKETPLACE_PATH}`);
  console.log(`  mcp     ${config.mcpUrl}`);
  console.log("");
  console.log("Next:");
  console.log("  1. claude plugin marketplace add .");
  console.log("  2. claude plugin install penopta@penopta-claude");
  console.log("  3. Approve Sign in with Penopta, then run /penopta-context or ask to verify.");
  console.log("Directory listing: see docs/private/claude-directory.md");
}

main().catch((err) => {
  console.error(err instanceof Error ? err.message : err);
  process.exit(1);
});
